services:
  - type: web
    name: finbuddy
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: ALPHA_VANTAGE_API_KEY
        fromSecret: ALPHA_VANTAGE_API_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: finbuddy-db
          property: connectionString

  - type: pserv
    name: finbuddy-db
    databaseName: finbuddy
    databaseUser: finbuddy