services:
  - type: web
    name: finbuddy-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: finbuddy-db
          property: connectionString

  - type: pserv
    name: finbuddy-db
    plan: free